### ISSUE TITLE
Production build

### ISSUE THREAD

**Issue by parabolabam** [parabolabam/client-app#14]
running
 
```sh
npm run prepare:production && npm build:prod
```
results in 
```sh
> NODE_ENV=production webpack --config './webpack.config.js'

/home/vsorokin/work/client-app/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (/home/vsorokin/work/client-app/node_modules/tslib/tslib.js:65:9)
    at /home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:115:17
    at /home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:314:6
    at /home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:3:17
    at Object.<anonymous> (/home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:9:3)
    at Module._compile (/home/vsorokin/work/client-app/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/vsorokin/work/client-app/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at /home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:20:22
    at /home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:10:17
    at Object.<anonymous> (/home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:16:3)
    at Module._compile (/home/vsorokin/work/client-app/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/vsorokin/work/client-app/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at /home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/program.js:31:23
    at /home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/program.js:10:17
    at Object.<anonymous> (/home/vsorokin/work/client-app/node_modules/@angular/compiler-cli/src/ngtsc/program.js:16:3)
    at Module._compile (/home/vsorokin/work/client-app/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client-app@0.0.0 webpack-prod: `NODE_ENV=production webpack --config './webpack.config.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client-app@0.0.0 webpack-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsorokin/.npm/_logs/2019-08-07T12_37_26_956Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client-app@0.0.0 build:prod: `npm run webpack-prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client-app@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsorokin/.npm/_logs/2019-08-07T12_37_27_524Z-debug.log
```

We should fix it

**Comment by parabolabam** [comment]
P.S. Right now we use 
```sh
npm i 
```

script instead of `npm i --production` and that result in packages quantity increase.
